CodeSwat\ShopBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: CodeSwat\ShopBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        price:
            type: decimal
            precision: '10'
            scale: '2'
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
